parameters:
    ongr_content.twig.content_extension.class: ONGR\ContentBundle\Twig\ContentExtension
    ongr_content.twig.category_extension.class: ONGR\ContentBundle\Twig\CategoryExtension
    ongr_content.content_service.class: ONGR\ContentBundle\Service\ContentService
    ongr_content.category_service.class: ONGR\ContentBundle\Service\CategoryService

    ongr_content.product_per_page: 10

services:

    twig.extension.stringloader:
        class: Twig_Extension_StringLoader
        tags:
           - { name: twig.extension }
    ongr_content.twig.content_extension:
        class: %ongr_content.twig.content_extension.class%
        tags:
          - { name: twig.extension }
        arguments:
          - @fragment.handler
          - @router
          - %ongr_content.snippet.render_strategy%

    ongr_content.content_service:
        class: %ongr_content.content_service.class%
        calls:
            - [setLogger, [@?logger]]

    ongr_content.category_service:
        class: %ongr_content.category_service.class%

    ongr_content.twig.category_extension:
        class: %ongr_content.twig.category_extension.class%
        tags:
            - { name: twig.extension }
        arguments:
            - @ongr_content.category_service
